### ISSUE TITLE
debug ? with paper-textarea

### ISSUE THREAD

**Issue by btopro** [MaritzSTL/mtz-marked-editor#6]
When trying to wire this up to a textarea field it works flawlessly but when trying to wire up to a  paper-textarea it always defaults to the 1st line position to apply it's text.. any ideas? 
```
        <mtz-marked-editor id="comment-editor" class="hide-element">
          <div slot="controls">
            <mtz-marked-control-generic-wrap
              icon="editor:format-bold"
              title="Bold"
              syntax-prefix="**"
              syntax-suffix="**"
              keys="ctrl+b"
            ></mtz-marked-control-generic-wrap>
            <mtz-marked-control-generic-wrap
              icon="editor:format-italic"
              title="Italic"
              syntax-prefix="_"
              syntax-suffix="_"
              keys="ctrl+i"
            ></mtz-marked-control-generic-wrap>
            <mtz-marked-control-generic-line
              icon="editor:format-size"
              title="Heading 3"
              syntax-prefix="### "
            ></mtz-marked-control-generic-line>
            <mtz-marked-control-link
              icon="editor:insert-link"
              title="Link"
            ></mtz-marked-control-link>
          </div>
          <paper-textarea id="comment-edit-input" label="Comment" value="{{comment.attributes.body}}" slot="textarea">
        </mtz-marked-editor>
```

**Comment by btopro** [comment]
To see what I mean: before and after clicking on the italic button:
![2017-07-27_12-04-35](https://user-images.githubusercontent.com/329735/28680278-d6f37758-72c3-11e7-9ccd-95b23e485e04.png)

after:
![2017-07-27_12-04-47](https://user-images.githubusercontent.com/329735/28680286-db827940-72c3-11e7-918e-afb8b0868bbf.png)

**Comment by btopro** [comment]
applies italic but does so to the entire value of the area and then injects it again a few times as prefix and suffix to the original :\

**Comment by stramel** [comment]
@btopro I really appreciate you taking a look at our first attempt at the marked editor. I haven't tried it out with paper-textarea yet so I will try to take a look tonight at what is going on. Looks like it isn't recognizing the selection properly

**Comment by stramel** [comment]
@btopro Put out a PR to get the `selectionStart` and `selectionEnd` exposed :grimacing: 

https://github.com/PolymerElements/paper-input/pull/557

It should function properly after that is merged.

**Comment by btopro** [comment]
Your awesome. I'll have to try the PR as a patch in my build but that looks like what I was butting up against. In the future I'll wait for a response instead of blowing 2 hours trying to find brute force work arounds :)

**Comment by stramel** [comment]
@btopro You can point to my fork if you would like. Modify your `bower.json` to do this.

`"paper-input": "stramel/paper-input#feature/selection",`

**Comment by btopro** [comment]
oh nice, thanks for the syntax. I forked it over to our LRNWebComponents repo and implemented it! You can check it out in our demo here -- https://lrnwebcomponents.github.io/lrnsys-comment/components/lrnsys-comment/

Go to the demo and click either reply or edit on a comment card to trigger your markdown editor to show up w/ paper-textarea

**Comment by btopro** [comment]
closing this out then cause this isn't an issue for this repo and there's a PR into the one that matters
